# Generated by Django 5.1.4 on 2024-12-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bookinginfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=300, null=True)),
                ('patient_age', models.CharField(blank=True, max_length=300, null=True)),
                ('patient_height', models.CharField(blank=True, max_length=300, null=True)),
                ('patient_weight', models.CharField(blank=True, max_length=300, null=True)),
                ('patient_addr', models.CharField(blank=True, max_length=300, null=True)),
                ('APPOINTMENTDATE', models.DateField(blank=True, max_length=100, null=True)),
                ('APPOINTMENTTIME', models.TimeField(blank=True, max_length=100, null=True)),
                ('visitReason', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorid', to='Predictivehealthapp.doctortable')),
            ],
        ),
        migrations.AddField(
            model_name='doctortable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.logintable'),
        ),
        migrations.CreateModel(
            name='medicineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(blank=True, max_length=20, null=True)),
                ('brandname', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('dosageform', models.CharField(blank=True, max_length=20, null=True)),
                ('strength', models.CharField(blank=True, max_length=20, null=True)),
                ('expdate', models.DateField(blank=True, max_length=20, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='postsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=20, null=True)),
                ('imgurl', models.FileField(blank=True, null=True, upload_to='posts')),
                ('tags', models.CharField(blank=True, max_length=20, null=True)),
                ('createdat', models.DateField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='prescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(blank=True, max_length=20, null=True)),
                ('issueddate', models.DateField(blank=True, max_length=20, null=True)),
                ('expirydate', models.DateField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('APPOINTMENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.bookinginfotable')),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='reviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewcomment', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewtime', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DOCTORID', to='Predictivehealthapp.doctortable')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='USERID', to='Predictivehealthapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='bookinginfotable',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='Predictivehealthapp.usertable'),
        ),
    ]
