# Generated by Django 5.1.4 on 2024-12-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptiontable',
            old_name='prescription',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='prescriptiontable',
            name='medicine_dosage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontable',
            name='medicine_itd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontable',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfotable',
            name='APPOINTMENTDATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfotable',
            name='APPOINTMENTTIME',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontable',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiontable',
            name='issueddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
