# Generated by Django 5.1.4 on 2024-12-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0002_rename_prescription_prescriptiontable_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poststable',
            old_name='tags',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='poststable',
            old_name='imgurl',
            new_name='file',
        ),
    ]
