# Generated by Django 5.1.4 on 2024-12-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0003_rename_tags_poststable_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poststable',
            old_name='file',
            new_name='filepost',
        ),
    ]
