# Generated by Django 5.1.4 on 2024-12-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0005_alter_poststable_category_alter_poststable_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('attachement', models.FileField(blank=True, null=True, upload_to='posts')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.doctortable')),
                ('PATIENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.usertable')),
            ],
        ),
    ]
