# Generated by Django 5.1.4 on 2025-01-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0003_alter_bookinginfotable_doctorid_and_more'),
        ('Predictivehealthapp', '0006_notificationtable'),
    ]

    operations = [
    ]
