# Generated by Django 5.1.4 on 2025-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0008_rename_city_usertable_gender_usertable_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='createdat',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
