# Generated by Django 5.1.4 on 2025-01-22 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0009_notificationtable_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('createdat', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('DOCTORID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.doctortable')),
            ],
        ),
    ]
