# Generated by Django 5.1.4 on 2025-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0010_slottable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slottable',
            name='description',
        ),
    ]
