# Generated by Django 5.1.4 on 2025-01-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0011_remove_slottable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottable',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
