# Generated by Django 5.1.4 on 2025-02-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0014_slottable_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottable',
            name='PATIENTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.usertable'),
        ),
    ]
