# Generated by Django 5.1.4 on 2025-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
