# Generated by Django 5.1.4 on 2025-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0018_alter_prescriptiontable_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='reviewcomment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
