# Generated by Django 5.1.4 on 2025-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0019_alter_reviewtable_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
