# Generated by Django 5.1.4 on 2025-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0020_doctortable_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortable',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
