# Generated by Django 5.1.4 on 2025-03-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0021_alter_doctortable_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctortable',
            old_name='rating',
            new_name='avg_rating',
        ),
    ]
