# Generated by Django 5.1.4 on 2025-03-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0022_rename_rating_doctortable_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.usertable'),
        ),
    ]
