# Generated by Django 5.1.4 on 2025-03-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictivehealthapp', '0023_chathistory_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtable',
            name='PATIENTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictivehealthapp.bookinginfotable'),
        ),
    ]
